### PR TITLE
V0.1.0-beta 1

### PR DESCRIPTION
**Pull request by TobiasFeld22**
- Added warning if node version was <= 8.
- Fixed about command bug where the fields keep adding up.
- Prefixes are now properly stored for custom configs.
and more!

### CODE REVIEW

**Comment by TobiasFeld22** [comment]
Waiting for #55 to be confirmed fixed.
Edit: closed

**Review by Sanil14 — DISMISSED** [review]
Everything is looking great.

**Comment by sharletk** [comment]
Tested the code with a Discord Bot and all looks good 👍

**Review by sharletk — DISMISSED** [review]
Checked through everything and done some tests as well, all looks good 👌

**Review by sharletk — COMMENTED** [review]
Did some tests again and rechecked the code, looks pretty good,

**Pull request merged**
