### PR TITLE
Fixing method of identifying prefix

### PR DESCRIPTION
**Pull request by Sanil14**
When I tried making a prefix which ended with a space:
EG:  `/HMB `
Instead of identifying the prefix and the first command as [0] it was identifying prefix as [0] and the command as [1]. This is only the case in "createcommand" and "reload" files. (from what I could find)

Hope I was helpful!

### CODE REVIEW

**Comment by Sanil14** [comment]
me and my nubby pull requests. Sorry for doing it on master by mistake lol

**Comment by TobiasFeld22** [comment]
Yes, it's a nice thing to have this fix, but i would rather also remove the cause of this first issue all together: allowing a space in the prefix in the first place. Try to add a prevention in the loading of the bot.

**Review by TobiasFeld22 — CHANGES_REQUESTED** [review]
Please add what i have mentioned in my comment.

**Comment by Sanil14** [comment]
Ah. Yeah. I guess that's a better step to take. Helps for future planning aswell.

**Review by TobiasFeld22 — APPROVED** [review]

**Pull request merged**
